# Generated by Django 2.2.3 on 2019-07-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/none/no-img.jpg', upload_to='images/'),
        ),
    ]
