# Generated by Django 2.2.3 on 2019-08-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
